# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: okteto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/java-springboot-k8s:latest, ${{ secrets.DOCKER_USERNAME }}/java-springboot-k8s:${{ github.run_number }}

    - name: Configuring K8S Deployment
      run: sed -i "s/latest/${{ github.run_number }}/g" ./k8s/deployment.yml

    - name: OKTeto - Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: OKTeto - Activate Namespace
      uses: okteto/namespace@master
      with:
        namespace: effetivo

    - name: OKTeto - Create deployment
      uses: okteto/apply@master
      with:
        manifest: k8s

#    - name: Sleep for 30 seconds
#      run: sleep 30s
#      shell: bash     

#    - name: OKTeto - Verify
#      uses: srt32/uptime@v0.2
#      with:
#        url-to-hit: "https://k8s-effetivo.cloud.okteto.net/api"
#        expected-statuses: "200"        
