server:
  port: 8002

spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
  zipkin:
    baseUrl: http://localhost:9411

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

management:
  endpoints:
    web:
      exposure:
        include: "refresh"