AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - aws-lambda-quarkus-http-1.0.0
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
    - '*/*'
Resources:
  AwsLambdaQuarkusHttp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: s3://effetivo-lambda/984f19ce38ca37a8ce024c807333aa7a
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        HttpApiEvent:
          Type: HttpApi
    Metadata:
      SamResourceId: AwsLambdaQuarkusHttp
Outputs:
  AwsLambdaQuarkusHttpApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
    Export:
      Name: AwsLambdaQuarkusHttpApi
