spring:
  application:
    name: service-two
  profiles:
    active: profile1
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      username: admin
      password: password
