version: "3.9"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres
    mem_limit: 256m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    mem_limit: 128m
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    mem_limit: 128m
    ports:
      - "3000:3000"
