#image: maven:3.8.1-adoptopenjdk-11
image: maven:3.8.1-adoptopenjdk-11

stages:
  - build
  - test
  - docker

Build:
  stage: build
  script:
    - mvn compile
  only:
    - main

#Sonar:
#  stage: test
#  tags:
#    - shell
#  only:
#    - main
#  script:
#    - echo running sonar || true

Test and Package:
  stage: test
  services:
    - docker:dind
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
  script:
    - mvn package
  only:
    - main

Docker Build:
  stage: docker
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_USER/:$CI_COMMIT_REF_SLUG
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
  before_script:
    - export DOCKER_TAG=`if [$CI_COMMIT_BRANCH == "main" ]; then echo $CI_COMMIT_SHORT_SHA; else echo $CI_COMMIT_TAG; fi;`
    - export DOCKER_IMAGE="$CI_REGISTRY_USER/java-springboot-k8s"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" docker.io
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE:$DOCKER_TAG"
    - docker push "$DOCKER_IMAGE:latest"
  only:
    - main