version: "3.3"
services:
#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: my_jenkins        
#    privileged: true
#    user: root
#    ports:
#      - 8082:8080
#      - 50002:50000
#    volumes:
#      - ~/jenkins_data:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock    
#      - /usr/bin/docker:/usr/bin/docker

  cassandra:
    image: cassandra
    container_name: my_cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CFG_RACKDC_PREFER_LOCAL=true      
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra