apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers:
        - name: k8s-api
          image: effetivo/java-springboot-k8s:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: CASSANDRA_HOST
              value: "cassandra"
