version: "3.9"
services:
  app:
    container_name: spring-app
    image: effetivo-spring
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  prometheus:
    extends:
      file: docker-compose-common.yml
      service: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    extends:
      file: docker-compose-common.yml
      service: grafana

volumes:
  postgres:
